provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-raster-vector-summary-stats:
    handler: ./fn-raster-vector-summary-stats
    lang: dockerfile
    image: disarm/fn-raster-vector-summary-stats:0.0.8
    environment:
      write_debug: true
      write_timeout: 70
      read_timeout: 70
      exec_timeout: 65
      combine_output: false
