provider:
  name: faas
  gateway: http://faas.srv.disarm.io
functions:
  fn-raster-vector-summary-stats_0_0_3:
    handler: ./fn-raster-vector-summary-stats
    lang: dockerfile
    image: disarm/fn-raster-vector-summary-stats:0.0.3
    environment:
      write_debug: true
      write_timeout: 60
      combine_output: false
